import type { Metadata } from "next";
import Link from "next/link";
import { dkimCluster } from "@/app/data/internalLinks";

const MAX_HUB_CARDS = 12;

export const metadata: Metadata = {
  title:
    "DKIM Hub – Fix DKIM Errors, Selectors, Alignment and Signatures for Modern Email Delivery (2026)",
  description:
    "Deep-dive DKIM hub for founders and IT admins. Understand DKIM selectors, alignment, key length, body hash failures, and get one-minute fixes for common DKIM errors.",
};

export default function DKIMHubPage() {
  return (
    <main style={{ padding: "36px 0 64px" }}>
      <div className="container">
        {/* TOP STRIP + BREADCRUMB */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 8,
            fontSize: 12,
            letterSpacing: "0.06em",
            textTransform: "uppercase",
            color: "#6b7280",
            marginBottom: 14,
          }}
        >
          <span
            style={{
              width: 6,
              height: 6,
              borderRadius: 999,
              background: "#E0B100",
              display: "inline-block",
            }}
          />
          <span>Email Authentication Hub</span>
          <span style={{ color: "#9ca3af" }}>/</span>
          <span style={{ color: "#111827", fontWeight: 700 }}>DKIM</span>
        </div>

        {/* HERO + ONE-MINUTE FIX */}
        <section
          style={{
            display: "grid",
            gap: 16,
            gridTemplateColumns: "1.25fr 1fr",
            alignItems: "start",
          }}
        >
          <div style={card}>
            <div className="prose">
              <h1 style={{ marginTop: 0 }}>
                Master DKIM signatures for trusted email delivery
              </h1>

              <p>
                Our 2026 DKIM audit data shows the same pattern again and again:
                teams publish a selector once, assume everything is fine, and
                then months later discover broken signatures, missing keys, or
                alignment failures quietly damaging inbox placement. This hub
                turns that confusion into a clear, repeatable DKIM playbook.
              </p>

              <p>
                DomainKeys Identified Mail (DKIM) adds a cryptographic signature
                to your messages so receiving servers can verify that the email
                really came from an authorized sender and was not altered in
                transit. When selectors are missing, keys are malformed, or
                signing domains do not align, legitimate emails can lose trust.
              </p>

              <div
                style={{
                  display: "flex",
                  flexWrap: "wrap",
                  gap: 12,
                  alignItems: "center",
                }}
              >
                <Link href="/" style={primaryBtn}>
                  Run SPF, DKIM &amp; DMARC check
                </Link>
                <span style={{ fontSize: 12, color: "#6b7280" }}>
                  No login. Live DNS only. Built for fast triage.
                </span>
              </div>
            </div>
          </div>

          <aside
            style={{
              ...card,
              borderColor: "rgba(224,177,0,0.35)",
              background: "rgba(224,177,0,0.08)",
            }}
          >
            <div className="prose">
              <h2 style={{ marginTop: 0, fontSize: 18 }}>
                One-Minute DKIM baseline (safe starting point)
              </h2>

              <p style={{ fontSize: 14, color: "#374151" }}>
                Use the exact selector and public key generated by your email
                provider. Do not manually rewrite the key string.
              </p>

              <pre style={codeBox}>
{`Type:  TXT
Host:  selector1._domainkey.example.com
Value: v=DKIM1; k=rsa; p=YOUR_PUBLIC_KEY`}
              </pre>

              <p style={{ fontSize: 14, color: "#374151" }}>
                For Google Workspace, Microsoft 365, SendGrid, Mailgun, or
                other ESPs, publish the exact DKIM record they provide, wait for
                DNS propagation, and then re-run the checker.
              </p>
            </div>
          </aside>
        </section>

        {/* FOUNDER + IT */}
        <section
          style={{
            marginTop: 18,
            display: "grid",
            gap: 16,
            gridTemplateColumns: "1fr 1fr",
          }}
        >
          <div style={card}>
            <div className="prose">
              <h2 style={{ marginTop: 0, fontSize: 18 }}>
                For panicked founders: what “DKIM is broken” really means
              </h2>
              <p>
                When our team audits poor inbox placement, DKIM problems are
                often hidden behind vague delivery warnings. The domain looks
                legitimate, but signatures fail because a selector is missing,
                the wrong system is sending mail, or a gateway changes the
                message after signing.
              </p>
              <p>
                The fastest path to stability is to identify every system that
                sends mail for your brand, confirm each one signs with DKIM, and
                make sure the published selector record matches what the sender
                actually uses.
              </p>
              <p>
                If you only take one action today: send a real test message,
                inspect the DKIM result in the headers, and confirm the selector
                and signing domain are exactly what you expect.
              </p>
            </div>
          </div>

          <div style={card}>
            <div className="prose">
              <h2 style={{ marginTop: 0, fontSize: 18 }}>
                For IT admins: selectors, alignment and signature failures
              </h2>
              <p>
                Major receivers expect DKIM to be both technically valid and
                operationally consistent. That means the selector must resolve,
                the public key must be complete, the key length must be modern,
                and the signing domain should align with the visible From:
                domain when DMARC is enabled.
              </p>
              <p>
                Our checks help you isolate whether the problem comes from a
                missing selector, malformed key, weak key length, alignment
                issue, or body hash mismatch caused by message modifications in
                transit.
              </p>
              <p>
                Treat DKIM as a living system, not a one-time DNS task. Version
                selector changes, document which provider signs what traffic,
                and rotate keys deliberately rather than during incidents.
              </p>
            </div>
          </div>
        </section>

        {/* CLUSTER LINKS */}
        <section style={{ marginTop: 18 }}>
          <div style={card}>
            <div
              style={{
                display: "flex",
                gap: 12,
                alignItems: "baseline",
                justifyContent: "space-between",
                marginBottom: 12,
              }}
            >
              <h2 style={{ margin: 0, fontSize: 18, color: "#111827" }}>
                DKIM troubleshooting playbook
              </h2>
              <span style={{ fontSize: 12, color: "#6b7280" }}>
                Deep dives for specific DKIM errors
              </span>
            </div>

            <div
              style={{
                display: "grid",
                gap: 12,
                gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
              }}
            >
              {/* Future: add "View all issues" page when clusters exceed MAX_HUB_CARDS */}
              {Array.from(
                new Map(dkimCluster.map((item) => [item.href, item])).values()
              )
                .slice(0, MAX_HUB_CARDS)
                .map((link) => (
                <HubLink
                  key={link.href}
                  href={link.href}
                  label={link.label}
                  description={link.description}
                />
              ))}
            </div>
          </div>
        </section>

        {/* CROSS-PROTOCOL */}
        <section
          style={{
            marginTop: 18,
            display: "grid",
            gap: 16,
            gridTemplateColumns: "1.4fr 1fr",
            alignItems: "start",
          }}
        >
          <div style={card}>
            <div className="prose">
              <h2 style={{ marginTop: 0, fontSize: 18 }}>
                How DKIM fits with SPF and DMARC
              </h2>
              <p>
                DKIM alone cannot fully protect your brand. Receivers interpret
                SPF, DKIM, and DMARC together as one trust story about whether
                your messages are legitimate.
              </p>
              <p>
                SPF authorizes sending infrastructure, DKIM signs message
                content, and DMARC decides what to do when those signals do not
                align with the visible From: domain. When all three work
                together, you can move from monitoring to stronger enforcement
                with much more confidence.
              </p>
              <p>
                If you are planning a full rollout, stabilize SPF first, make
                sure every sender signs correctly with DKIM, and then tighten
                DMARC once alignment is proven.
              </p>
            </div>
          </div>

          <div
            style={{
              borderRadius: 14,
              padding: 16,
              border: "1px solid #111827",
              background: "#111827",
              color: "#fff",
            }}
          >
            <div style={{ fontWeight: 800, marginBottom: 6 }}>
              Next protocol hubs
            </div>
            <div
              style={{
                fontSize: 13,
                color: "rgba(255,255,255,0.8)",
                marginBottom: 12,
              }}
            >
              Continue the journey with focused guides for the other protocols.
            </div>

            <div style={{ display: "grid", gap: 10 }}>
              <Link href="/spf" style={darkCardLink}>
                <span>SPF Hub – sender authorization</span>
                <span style={{ fontSize: 11, opacity: 0.75 }}>Origins</span>
              </Link>
              <Link href="/dmarc" style={darkCardLink}>
                <span>DMARC Hub – enforcement policy</span>
                <span style={{ fontSize: 11, opacity: 0.75 }}>Control</span>
              </Link>
            </div>
          </div>
        </section>
      </div>

      {/* responsive tweaks */}
      <style>{`
        @media (max-width: 980px) {
          section[style*="grid-template-columns: 1.25fr 1fr"] { grid-template-columns: 1fr !important; }
          section[style*="grid-template-columns: 1fr 1fr"] { grid-template-columns: 1fr !important; }
          section[style*="grid-template-columns: 1.4fr 1fr"] { grid-template-columns: 1fr !important; }
        }
      `}</style>
    </main>
  );
}

function HubLink({
  href,
  label,
  description,
}: {
  href: string;
  label: string;
  description?: string;
}) {
  return (
    <Link
      href={href}
      style={{
        display: "flex",
        flexDirection: "column",
        gap: 6,
        padding: 12,
        borderRadius: 12,
        border: "1px solid #e5e7eb",
        background: "rgba(249,250,251,0.8)",
        textDecoration: "none",
      }}
    >
      <span style={{ fontWeight: 700, color: "#111827" }}>{label}</span>
      {description && (
        <span style={{ fontSize: 13, color: "#6b7280" }}>{description}</span>
      )}
    </Link>
  );
}

/** shared styles */
const card: React.CSSProperties = {
  border: "1px solid #e5e7eb",
  background: "#ffffff",
  borderRadius: 14,
  padding: 18,
  boxShadow: "0 1px 0 rgba(0,0,0,0.02)",
};

const primaryBtn: React.CSSProperties = {
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
  height: 40,
  padding: "0 14px",
  borderRadius: 10,
  border: "1px solid #c79c00",
  background: "#E0B100",
  color: "#111827",
  fontWeight: 800,
  textDecoration: "none",
};

const codeBox: React.CSSProperties = {
  margin: "10px 0",
  padding: 12,
  borderRadius: 12,
  background: "#111827",
  color: "#f9fafb",
  fontSize: 12,
  lineHeight: 1.5,
  overflowX: "auto",
};

const darkCardLink: React.CSSProperties = {
  display: "flex",
  alignItems: "center",
  justifyContent: "space-between",
  gap: 10,
  padding: "10px 12px",
  borderRadius: 12,
  border: "1px solid rgba(255,255,255,0.18)",
  background: "rgba(255,255,255,0.06)",
  color: "#fff",
  textDecoration: "none",
};