import type { Metadata } from "next";
import Link from "next/link";
import { dkimCluster } from "@/app/data/internalLinks";

const MAX_HUB_CARDS = 12;

export const metadata: Metadata = {
  title:
    "DKIM Hub – Fix DKIM Errors, Selectors, Alignment and Signatures for Modern Email Delivery (2026)",
  description:
    "Deep-dive DKIM hub for founders and IT admins. Understand DKIM selectors, alignment, key length, body hash failures, and get one-minute fixes for common DKIM errors.",
};

export default function DKIMHubPage() {
  const foundationalLinks = [
    {
      href: "/dkim/dkim-guide",
      label: "Complete DKIM Guide",
      description:
        "Full guide to DKIM signatures, selectors, keys, alignment, and troubleshooting.",
    },
    {
      href: "/dkim/dkim-record-example",
      label: "DKIM record examples",
      description:
        "Real DNS TXT examples for common DKIM setups and how to read them.",
    },
    {
      href: "/dkim/dkim-signature-explained",
      label: "DKIM signature explained",
      description:
        "Understand header fields, verification flow, and body hash behavior.",
    },
  ];

  const troubleshootingLinks = dkimCluster
    .filter(
      (item) =>
        ![
          "/dkim/dkim-record-example",
          "/dkim/dkim-signature-explained",
        ].includes(item.href)
    )
    .slice(0, MAX_HUB_CARDS);

  return (
    <main style={{ padding: "36px 0 64px" }}>
      <div className="container">
        {/* TOP STRIP + BREADCRUMB */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 8,
            fontSize: 12,
            letterSpacing: "0.06em",
            textTransform: "uppercase",
            color: "#6b7280",
            marginBottom: 14,
          }}
        >
          <span
            style={{
              width: 6,
              height: 6,
              borderRadius: 999,
              background: "#E0B100",
              display: "inline-block",
            }}
          />
          <span>Email Authentication Hub</span>
          <span style={{ color: "#9ca3af" }}>/</span>
          <span style={{ color: "#111827", fontWeight: 700 }}>DKIM</span>
        </div>

        {/* HERO + ONE-MINUTE FIX */}
        <section
          style={{
            display: "grid",
            gap: 16,
            gridTemplateColumns: "1.25fr 1fr",
            alignItems: "start",
          }}
        >
          <div style={card}>
            <div className="prose">
              <h1 style={{ marginTop: 0 }}>
                Master DKIM signatures for trusted email delivery
              </h1>

              <p>
                DKIM is the integrity layer of email authentication. It lets
                receiving servers verify that a message really came from an
                authorized sender and was not modified after it was signed. When
                DKIM is healthy, it strengthens trust, supports DMARC
                enforcement, and makes legitimate mail more resilient across
                forwarding and multi-provider setups.
              </p>

              <p>
                This hub brings together the core educational pages, the most
                common DKIM troubleshooting paths, and the protocol context you
                need before tightening DMARC policy. Use it if you are trying to
                understand selectors, fix missing keys, investigate alignment
                failures, or verify that your providers are signing the right
                traffic in the right way.
              </p>

              <div
                style={{
                  display: "flex",
                  flexWrap: "wrap",
                  gap: 12,
                  alignItems: "center",
                }}
              >
                <Link href="/" style={primaryBtn}>
                  Run SPF, DKIM &amp; DMARC check
                </Link>
                <span style={{ fontSize: 12, color: "#6b7280" }}>
                  No login. Live DNS only. Built for fast triage.
                </span>
              </div>
            </div>
          </div>

          <aside
            style={{
              ...card,
              borderColor: "rgba(224,177,0,0.35)",
              background: "rgba(224,177,0,0.08)",
            }}
          >
            <div className="prose">
              <h2 style={{ marginTop: 0, fontSize: 18 }}>
                One-Minute DKIM baseline (safe starting point)
              </h2>

              <p style={{ fontSize: 14, color: "#374151" }}>
                Use the exact selector and public key generated by your email
                provider. Do not manually rewrite the key string.
              </p>

              <pre style={codeBox}>
{`Type:  TXT
Host:  selector1._domainkey.example.com
Value: v=DKIM1; k=rsa; p=YOUR_PUBLIC_KEY`}
              </pre>

              <p style={{ fontSize: 14, color: "#374151" }}>
                For Google Workspace, Microsoft 365, SendGrid, Mailgun, or
                other ESPs, publish the exact DKIM record they provide, wait for
                DNS propagation, and then re-run the checker.
              </p>
            </div>
          </aside>
        </section>

        {/* START HERE */}
        <section style={{ marginTop: 18 }}>
          <div style={card}>
            <div
              style={{
                display: "flex",
                gap: 12,
                alignItems: "baseline",
                justifyContent: "space-between",
                marginBottom: 12,
              }}
            >
              <h2 style={{ margin: 0, fontSize: 18, color: "#111827" }}>
                Start here
              </h2>
              <span style={{ fontSize: 12, color: "#6b7280" }}>
                Foundational DKIM pages
              </span>
            </div>

            <div
              style={{
                display: "grid",
                gap: 12,
                gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
              }}
            >
              {foundationalLinks.map((link) => (
                <HubLink
                  key={link.href}
                  href={link.href}
                  label={link.label}
                  description={link.description}
                />
              ))}
            </div>
          </div>
        </section>

        {/* FOUNDER + IT */}
        <section
          style={{
            marginTop: 18,
            display: "grid",
            gap: 16,
            gridTemplateColumns: "1fr 1fr",
          }}
        >
          <div style={card}>
            <div className="prose">
              <h2 style={{ marginTop: 0, fontSize: 18 }}>
                For founders: what “DKIM is broken” usually means
              </h2>
              <p>
                DKIM problems often hide behind vague delivery warnings. A
                domain can look legitimate on the surface, yet signatures fail
                because a selector is missing, the wrong platform is signing, or
                a downstream gateway changes the message after it leaves your
                system.
              </p>
              <p>
                The practical fix is to inventory every service that sends mail
                as your brand, confirm which one actually signs each message,
                and make sure the published selector record matches the signer
                that appears in the live headers. DKIM is rarely broken because
                of one dramatic mistake. It is usually broken because ownership
                drifted across tools over time.
              </p>
            </div>
          </div>

          <div style={card}>
            <div className="prose">
              <h2 style={{ marginTop: 0, fontSize: 18 }}>
                For IT admins: selectors, alignment and signature failures
              </h2>
              <p>
                Major receivers expect DKIM to be both technically valid and
                operationally consistent. The selector must resolve, the public
                key must be complete, the key length should be modern, and the
                signing domain should align with the visible From: domain when
                DMARC is enabled.
              </p>
              <p>
                The common traps are straightforward but painful: a missing
                selector during key rotation, a truncated TXT record, a weak
                legacy key, or a message body changed by a secure gateway after
                signing. In each case, the message may still be legitimate, but
                the authentication story no longer holds together.
              </p>
            </div>
          </div>
        </section>

        {/* HOW DKIM WORKS */}
        <section style={{ marginTop: 18 }}>
          <div style={card}>
            <div className="prose">
              <h2 style={{ marginTop: 0, fontSize: 18 }}>
                How DKIM verification works in practice
              </h2>
              <p>
                When a message is sent, the sender adds a DKIM-Signature header.
                That header includes a selector (<code>s=</code>), a signing
                domain (<code>d=</code>), a body hash (<code>bh=</code>), and
                the cryptographic signature itself. The receiving server uses
                the selector and signing domain to retrieve the public key from
                DNS under <code>selector._domainkey.example.com</code>.
              </p>
              <p>
                If the public key is present and valid, the receiver verifies
                the signature against the signed headers and message body. If
                the message body changed after signing, the body hash fails. If
                the selector is missing, the key is malformed, or the signature
                references the wrong domain, DKIM fails even when the sender is
                otherwise legitimate. For the full flow, read the{" "}
                <Link href="/dkim/dkim-guide">Complete DKIM Guide</Link>.
              </p>
            </div>
          </div>
        </section>

        {/* CLUSTER LINKS */}
        <section style={{ marginTop: 18 }}>
          <div style={card}>
            <div
              style={{
                display: "flex",
                gap: 12,
                alignItems: "baseline",
                justifyContent: "space-between",
                marginBottom: 12,
              }}
            >
              <h2 style={{ margin: 0, fontSize: 18, color: "#111827" }}>
                DKIM troubleshooting playbook
              </h2>
              <span style={{ fontSize: 12, color: "#6b7280" }}>
                Deep dives for specific DKIM errors
              </span>
            </div>

            <div
              style={{
                display: "grid",
                gap: 12,
                gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
              }}
            >
              {troubleshootingLinks.map((link) => (
                <HubLink
                  key={link.href}
                  href={link.href}
                  label={link.label}
                  description={link.description}
                />
              ))}
            </div>
          </div>
        </section>

        {/* CROSS-PROTOCOL */}
        <section
          style={{
            marginTop: 18,
            display: "grid",
            gap: 16,
            gridTemplateColumns: "1.4fr 1fr",
            alignItems: "start",
          }}
        >
          <div style={card}>
            <div className="prose">
              <h2 style={{ marginTop: 0, fontSize: 18 }}>
                When DKIM alone is not enough
              </h2>
              <p>
                DKIM is only one part of the full authentication stack. It helps
                prove message integrity and domain ownership, but it does not
                authorize sending infrastructure by itself and it does not tell
                receivers how to enforce failures against your visible brand.
              </p>
              <p>
                SPF validates the sending path. DKIM validates the message.
                DMARC evaluates whether either authentication path aligns with
                the visible From: domain and then applies your published policy.
                That is why a technically valid signature is still not enough if
                the signing domain does not align, or if your SPF and DKIM
                implementation across providers is inconsistent.
              </p>
              <p>
                For stable deployment, clean SPF first, make sure every real
                sender signs correctly with DKIM, and only then tighten DMARC
                once alignment is proven across the traffic that actually
                matters.
              </p>
            </div>
          </div>

          <div
            style={{
              borderRadius: 14,
              padding: 16,
              border: "1px solid #111827",
              background: "#111827",
              color: "#fff",
            }}
          >
            <div style={{ fontWeight: 800, marginBottom: 6 }}>
              Next protocol hubs
            </div>
            <div
              style={{
                fontSize: 13,
                color: "rgba(255,255,255,0.8)",
                marginBottom: 12,
              }}
            >
              Continue the journey with focused guides for the other protocols.
            </div>

            <div style={{ display: "grid", gap: 10 }}>
              <Link href="/spf" style={darkCardLink}>
                <span>SPF Hub – sender authorization</span>
                <span style={{ fontSize: 11, opacity: 0.75 }}>Origins</span>
              </Link>
              <Link href="/dmarc" style={darkCardLink}>
                <span>DMARC Hub – enforcement policy</span>
                <span style={{ fontSize: 11, opacity: 0.75 }}>Control</span>
              </Link>
            </div>
          </div>
        </section>
      </div>

      {/* responsive tweaks */}
      <style>{`
        @media (max-width: 980px) {
          section[style*="grid-template-columns: 1.25fr 1fr"] { grid-template-columns: 1fr !important; }
          section[style*="grid-template-columns: 1fr 1fr"] { grid-template-columns: 1fr !important; }
          section[style*="grid-template-columns: 1.4fr 1fr"] { grid-template-columns: 1fr !important; }
        }
      `}</style>
    </main>
  );
}

function HubLink({
  href,
  label,
  description,
}: {
  href: string;
  label: string;
  description?: string;
}) {
  return (
    <Link
      href={href}
      style={{
        display: "flex",
        flexDirection: "column",
        gap: 6,
        padding: 12,
        borderRadius: 12,
        border: "1px solid #e5e7eb",
        background: "rgba(249,250,251,0.8)",
        textDecoration: "none",
      }}
    >
      <span style={{ fontWeight: 700, color: "#111827" }}>{label}</span>
      {description && (
        <span style={{ fontSize: 13, color: "#6b7280" }}>{description}</span>
      )}
    </Link>
  );
}

/** shared styles */
const card: React.CSSProperties = {
  border: "1px solid #e5e7eb",
  background: "#ffffff",
  borderRadius: 14,
  padding: 18,
  boxShadow: "0 1px 0 rgba(0,0,0,0.02)",
};

const primaryBtn: React.CSSProperties = {
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
  height: 40,
  padding: "0 14px",
  borderRadius: 10,
  border: "1px solid #c79c00",
  background: "#E0B100",
  color: "#111827",
  fontWeight: 800,
  textDecoration: "none",
};

const codeBox: React.CSSProperties = {
  margin: "10px 0",
  padding: 12,
  borderRadius: 12,
  background: "#111827",
  color: "#f9fafb",
  fontSize: 12,
  lineHeight: 1.5,
  overflowX: "auto",
};

const darkCardLink: React.CSSProperties = {
  display: "flex",
  alignItems: "center",
  justifyContent: "space-between",
  gap: 10,
  padding: "10px 12px",
  borderRadius: 12,
  border: "1px solid rgba(255,255,255,0.18)",
  background: "rgba(255,255,255,0.06)",
  color: "#fff",
  textDecoration: "none",
};