import Link from "next/link";

export const metadata = {
  title: "No DKIM Record Found – Fix DKIM in 1 Minute",
  description:
    "No DKIM record found for your domain. Learn why DKIM is missing, how it affects email delivery, and how to fix it in one minute with a copy-paste DNS record.",
};

export default function NoDkimRecordFoundPage() {
  return (
    <main style={styles.wrapper}>
      <section style={styles.card}>
        <h1 style={styles.title}>No DKIM Record Found</h1>

        <p style={styles.subtitle}>
          Your domain does not have a DKIM record. This can cause emails to fail
          authentication or land in spam folders.
        </p>

        {/* One-Minute Fix */}
        <div style={styles.fixBox}>
          <h2 style={styles.sectionTitle}>One-Minute Fix</h2>
          <p style={styles.text}>
            Add a DKIM record generated by your email provider.
          </p>

          <pre style={styles.code}>
{`Type:  TXT
Host:  selector1._domainkey
Value: v=DKIM1; k=rsa; p=YOUR_PUBLIC_KEY
TTL:   Auto`}
          </pre>

          <p style={styles.note}>
            Replace <strong>YOUR_PUBLIC_KEY</strong> with the DKIM key provided
            by your email service. You cannot invent this value.
          </p>

          <Link href="/" style={styles.button}>
            Re-check DKIM
          </Link>
        </div>

        {/* What we checked */}
        <div style={styles.infoBox}>
          <h2 style={styles.sectionTitle}>What we checked</h2>
          <p style={styles.text}>
            We searched for DKIM records using common selector names used by
            major email providers.
          </p>
          <p style={styles.trust}>
            Live DNS lookup. No login. No saved domains. No tracking.
          </p>
        </div>

        {/* Still failing */}
        <div style={styles.escapeBox}>
          <h3 style={styles.escapeTitle}>Still failing?</h3>
          <ul style={styles.list}>
            <li>Your provider may use a different DKIM selector</li>
            <li>DNS changes may not have propagated yet</li>
            <li>More than one service may be sending email</li>
          </ul>
          <p style={styles.text}>
            This is common. You can wait a few minutes and re-check, or test
            another domain.
          </p>
        </div>
      </section>
    </main>
  );
}

/* ---------- STYLES ---------- */

const styles: Record<string, React.CSSProperties> = {
  wrapper: {
    maxWidth: 860,
    margin: "80px auto",
    padding: "0 24px",
  },
  card: {
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: 12,
    padding: 32,
  },
  title: {
    fontSize: 32,
    fontWeight: 700,
    marginBottom: 12,
  },
  subtitle: {
    color: "#374151",
    marginBottom: 32,
    lineHeight: 1.6,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 600,
    marginBottom: 12,
  },
  fixBox: {
    background: "#f9fafb",
    borderRadius: 10,
    padding: 24,
    marginBottom: 40,
  },
  code: {
    background: "#0f172a",
    color: "#e5e7eb",
    padding: 16,
    borderRadius: 8,
    fontSize: 14,
    marginTop: 12,
    marginBottom: 12,
    overflowX: "auto",
  },
  note: {
    fontSize: 14,
    color: "#374151",
    marginBottom: 16,
  },
  button: {
    display: "inline-block",
    padding: "12px 20px",
    background: "#E0B100",
    color: "#000",
    borderRadius: 6,
    fontWeight: 600,
    textDecoration: "none",
  },
  infoBox: {
    marginBottom: 40,
  },
  trust: {
    fontSize: 14,
    color: "#6b7280",
    marginTop: 8,
  },
  escapeBox: {
    borderTop: "1px solid #e5e7eb",
    paddingTop: 24,
  },
  escapeTitle: {
    fontSize: 18,
    fontWeight: 600,
    marginBottom: 8,
  },
  list: {
    paddingLeft: 18,
    marginBottom: 12,
    lineHeight: 1.6,
  },
  text: {
    color: "#374151",
    lineHeight: 1.6,
  },
};
